### ISSUE TITLE
Unable to create resource

### ISSUE THREAD

**Issue by Ludoviccharruau** [ankitpokhrel/tus-php#132]
Hi,
I'm trying to get the demo to work and I get an error in Client.php when calling the create() method in the upload() method. I don't know if this is due to a configuration error on my part. After a search in the closed issues, I decide to post a new one.

server.php
```php
<?php

require __DIR__ . '/../vendor/autoload.php';

$server   = new \TusPhp\Tus\Server();

$response = $server->serve();

$response->send();

exit(0); // Exit from current PHP process.
```

verify.php
```php
<?php

/**
 * Sends HEAD request to figure out uploaded offset
 * if the file was uploaded partially previously.
 */

require __DIR__ . '/../../vendor/autoload.php';

use TusPhp\Exception\FileException;
use GuzzleHttp\Exception\ConnectException;

$client = new \TusPhp\Tus\Client('http://localhost/test-tus/');

// Alert: Sanitize all inputs properly in production code
if ( ! empty($_FILES)) {
    $status    = 'new';
    $fileMeta  = $_FILES['tus_file'];
    $uploadKey = hash_file('md5', $fileMeta['tmp_name']);

    try {
        $offset = $client->setKey($uploadKey)->file($fileMeta['tmp_name'])->getOffset();

        if (false !== $offset) {
            $status = $offset >= $fileMeta['size'] ? 'uploaded' : 'resume';
        } else {
            $offset = 0;
        }

        echo json_encode([
            'status' => $status,
            'bytes_uploaded' => $offset,
            'upload_key' => $uploadKey,
        ]);
    } catch (ConnectException $e) {
        echo json_encode([
            'status' => 'error',
            'bytes_uploaded' => -1,
        ]);
    } catch (FileException $e) {
        echo json_encode([
            'status' => 'resume',
            'bytes_uploaded' => 0,
            'upload_key' => '',
        ]);
    }
} else {
    echo json_encode([
        'status' => 'error',
        'bytes_uploaded' => -1,
    ]);
}
```

upload.php
```php
<?php

/**
 * Uploads files in 5mb chunk.
 */

require __DIR__ . '/../../vendor/autoload.php';

use TusPhp\Exception\TusException;
use TusPhp\Exception\FileException;
use TusPhp\Exception\ConnectionException;

$client = new \TusPhp\Tus\Client('http://localhost/test-tus/');

// Alert: Sanitize all inputs properly in production code
if ( ! empty($_FILES)) {
    $fileMeta  = $_FILES['tus_file'];
    $uploadKey = hash_file('md5', $fileMeta['tmp_name']);

    try {
        $client->setKey($uploadKey)->file($fileMeta['tmp_name'], time() . '_' . $fileMeta['name']);

        $bytesUploaded = $client->upload(5000000); // Chunk of 5 mb

        echo json_encode([
            'status' => 'uploading',
            'bytes_uploaded' => $bytesUploaded,
            'upload_key' => $uploadKey
        ]);
    } catch (ConnectionException | FileException | TusException $e) {
        echo json_encode([
            'status' => 'error',
            'bytes_uploaded' => -1,
            'upload_key' => '',
            'error' => $e->getMessage(),
            'trace' => $e->getCode(),
        ]);
    }
} else {
    echo json_encode([
        'status' => 'error',
        'bytes_uploaded' => -1,
        'error' => 'No input!',
    ]);
}
```

Thank you in advance for your assistance.

**Comment by ankitpokhrel** [comment]
@Ludoviccharruau can you double check if you have write permission in your uploads folder?

**Comment by Ludoviccharruau** [comment]
@ankitpokhrel Yes, I have write permission on that folder. Maybe the path to the file is not the right one? Does it have a default location?

**Comment by ankitpokhrel** [comment]
@Ludoviccharruau yes, it sets following path if upload dir is not defined.

https://github.com/ankitpokhrel/tus-php/blob/1c36d2d542d848036c6e1fe85e8e1bb22f64833a/src/Tus/Server.php#L87

You can change upload dir in your app. That should fix the issue.

```php
$server-> setUploadDir('/path/to/your/upload/dir');
```

**Comment by Ludoviccharruau** [comment]
After a chmod 777, it seems that a permission issue has been resolved. However, an error persists in Client.php: l.501 in the `sendPatchRequest(int $bytes, int $offset)` method  when using the getUrl() method, which throws a FileException with the message: "File not found".

**Comment by Ludoviccharruau** [comment]
@ankitpokhrel After a chmod 777, it seems that a permission issue has been resolved. However, an error persists in Client.php: l.501 in the `sendPatchRequest(int $bytes, int $offset)` method  when using the` getUrl()` method, which throws a FileException with the message: "File not found".

**Comment by ankitpokhrel** [comment]
@Ludoviccharruau are you using file based cache or redis? Looks like the file url is not saved in your cache. Can you make sure your app can be connected to the cache in case you are using redis. And for file based case make sure that your app can create file inside a `cache` folder.

https://github.com/ankitpokhrel/tus-php/blob/1c36d2d542d848036c6e1fe85e8e1bb22f64833a/src/Config/client.php#L17-L20

**Comment by Ludoviccharruau** [comment]
@ankitpokhrel I think I use a based cache. In I got this from the cache: `{"tus:client:42585b81d9f4daea44a7dd03bd6ed2b9":{"location":false,"expires_at":"Thu, 14 Mar 2019 09:45:44 GMT"},"tus:client:b92257139dc4e5b16f54da6119feec42":{"location":false,"expires_at":"Thu, 14 Mar 2019 09:45:56 GMT"}}` 
Could it be due to the fact that I use LAMP ?

**Comment by ankitpokhrel** [comment]
@Ludoviccharruau no, it doesn't matter what server stack you use. The issue might be because cache file is created inside your `vendor` folder.

Can you copy [config files](https://github.com/ankitpokhrel/tus-php/tree/master/src/Config) from your `vendor` directory to your project folder and set config path before server and client creation.

```php
\TusPhp\Config::set(<path to your server/client config.php>);

// Create server or client object.
```

In the config file you just copied, change `cache` dir for both server and client to some folder with write permission.

```php
/**
 * File cache configs.
 */
'file' => [
    'dir' => '/path/to/your/project/writable/cache/dir',
    'name' => 'tus_php.client.cache',
],
```

**Comment by Ludoviccharruau** [comment]
@ankitpokhrel I made the changes, and I still get the same _File not found_ error.  Client and Server must have the same cache? In the original configuration, I had the impression that there were two different ones : _tus_php.client.cache_ et _tus_php.serveur.cache_ ?

**Comment by pdiveris** [comment]
No, they don't have to be the same but they both need to point to existing directories in which your webserver has got write access. Can you attach the config blocks of both your server and the client please?

**Comment by Ludoviccharruau** [comment]
@pdiveris I followed @ankitpokhrel's advice above: I specified
another path to a cache folder in a config file that I placed at the root of my project.
```<?php return [     /**      * Redis connection parameters.      */     'redis' => [         'host' => getenv('REDIS_HOST') ?? '127.0.0.1',         'port' => getenv('REDIS_PORT') ?? '6379',         'database' => 1,     ],     /**      * File cache configs.      */     'file' => [         'dir' => '/home/ludovic/labo/test-tus/cache/',         'name' => 'tus_php.client.cache',     ], ];```
Then, before the instantiation of the server or client, I specify the new configuration:
```Config::set('/home/ludovic/labo/test-tus/Config/config.php');```
I hope I'm clear enough?

**Comment by pdiveris** [comment]
Ye sure you are clear . I don't know what happened here, in the beginning I could only see a block of code that was invalid (the redis line wasn't closing), you seem to have updated it whilst I was answering you. So, on the basis of this updated block you just posted I would check two things
1. Does `/home/ludovic/labo/test-tus/cache/` exist and does you webserver user (www-data perhaps?) have write access to it?
2. Are you setting the cache explicitly to using file instead of redis? I think the examples specify redis by default i.e. `$server   = new \TusPhp\Tus\Server('redis');`

**Comment by Ludoviccharruau** [comment]
1. yes /home/ludovic/labo/test-tus/cache/ exists and www-data has write permission on the cache/ folder 

2.I don't use redis, I use the custom configuration `Config::set('/home/ludovic/labo/test-tus/Config/config.php');` and I instantiate the server this way: '$server = new \TusPhp\Tus\Server(); '

**Comment by pdiveris** [comment]
OK, so if I were you my net move would be to 
1. Change the line `$server = new \TusPhp \Tus\Server();` to explicitly using file, i.e. `$server = new \TusPhp \Tus\Server('file'); and
2. I'd be tempted to see whether the user `www-data` has `x` and `w` permissions on the parent folders too. Two easy ways to check without spending the whole night are a) try create a file through a `sudo -u www-data` command and even better and easier b) change the uploads folder to `/tmp` for the purpose of checking as `/tmp` is widely open. If that works then at least we know where the problem is. 

Good luck!

**Comment by ankitpokhrel** [comment]
Closing due to inactivity, please feel free to comment and reopen the issue
